### PR TITLE
Orange pi 4.6

### PR DESCRIPTION
**Pull request by erazor83**
Hi there.

I'm working with kernel-4.6 on the NanoPI Neo now and were missing some basic features like some of the boards USB-ports and I2C.

For these I've added a new dts file and had to add some parts in sun8i-h3.dtsi .

I found some DTS stuff on patchwork:
https://patchwork.kernel.org/patch/9313003/

### CODE REVIEW

**Comment by e-chip** [comment]
Hello! After this merge the build seems to be broken. I am building Armbian 5.17 for Orange Pi PC which uses this kernel.
Here is part of the buld log:
`
  DTC     arch/arm/boot/dts/sun8i-h3-orangepi-one.dtb
ERROR (duplicate_node_names): Duplicate node name /soc/i2c@01c2ac00
ERROR (duplicate_node_names): Duplicate node name /soc/i2c@01c2b000
ERROR (duplicate_node_names): Duplicate node name /soc/i2c@01c2b400
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/uart1@0
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/uart2@0
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/uart3@0
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/i2c0@0
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/i2c1@0
ERROR (duplicate_node_names): Duplicate node name /soc/pinctrl@01c20800/i2c2@0
`
Sorry if I am wrong but build was OK in the morning.

**Comment by erazor83** [comment]
Sorry for this.


I'll have a look.

**Comment by bz31** [comment]
Hello,
What are the differences between "FriendlyARM NanoPi NEO" and "ePC NEO by e-design" ?
Thanks.

**Comment by erazor83** [comment]
Just tried natively and it worked:
  DTC     arch/arm/boot/dts/sun8i-h3-orangepi-one.dtb

Maybe you've added some other patches after the git clone locally?

**Comment by e-chip** [comment]
Hm, may be you are right. Armbian applies lots of patches. I will forward thi error to Armbian project maintainers. Thanks for your help!

**Comment by erazor83** [comment]
Well, we build a custom addon-board for the NanoPI which has some more led's.
As you can see the DTB adds 3 LEDs, and a DS1307 RTC via I2C.

Adding this file might help someone writing custom DTB files...

**Comment by erazor83** [comment]
You're welcome. Let me know if I broke anything else. I'm running this kernel for some hours now on the Neo without trouble.

**Comment by bz31** [comment]
Ok. So I don't need to use et epc version dts for my nanopi neo, thanks. 
On my nanopi neo (using 4.9 branch), I have an empty /sys/devices/system/cpu/cpufreq/. Do you know to check if cpufreq and thermal work ?

**Comment by e-chip** [comment]
Yep, you are right! I removed all DTS related patches from Armbian and it builds fine.

**Comment by erazor83** [comment]
@e-chip maybe I should have a look what these patches do...

**Comment by megous** [comment]
@bz31 I only added operating points for Orange PI One and PC. If you're using other boards, you need to figure out necessary changes for its DTS file.

It will probably be similar to Orange PI PC or Orange PI One.

Relevant patches to get inspired by are:

 ARM: dts: sun8i: Setup CPU operating points for Onrage PI PC 
 ARM: dts: sun8i: Add gpio-regulator used on Orange Pi One 
 ARM: dts: sun8i: Enable DVFS on Orange Pi One

**Comment by erazor83** [comment]
@megous where can I find these patches? I'd try them out with the NEO. I guess since it's the same CPU things should work the same.

Thermal gives at least a temperature with value 17xxxx and it seems like the last 4 digits are temperature / 100 so 172510 becomes 25.10°C but that's just a guess. No idea where this offset came from.
I'm also wondering where a good place for these discussions is. The friendlyarm forums seem to quiet for me to get some responses.

@bz31 whats the state on the 4.9 branch? does everything work?

**Comment by megous** [comment]
Temerature:
```
cat /sys/class/thermal/thermal_zone0/temp
35006
```
That is 35°C

Your value seems weird.

These patches are in every one of the orangepi-4.* branches in this tree.

You can't blindly apply them. You need to verify with schematics of NEO, what kind of voltage regulation for CPUX it uses, and then adapt the DTS configuration to that. From a quick look at the schematics, it seems identical to Orange Pi One.

**Comment by bz31** [comment]
I am a novice and I don't understand the dts files. 
Using orangepi one dts, ethernet works and thermal seems OK. But cpu freq is minimal. That's for 4.9-rc1.  
Today 4.9-rc4 image doesn't boot on my nanopi neo.

**Comment by megous** [comment]
You should probably create a separate issue, so that we don't spam people on this pull request and provide more precise information, like dmesg output, exact version of the kernel you're using, kernel config, etc.

**Pull request merged**
