### PR TITLE
Orange Pi Zero XR819 WiFi

### PR DESCRIPTION
**Pull request by halmartin**
My apologies if this isn't the appropriate way to pull in external source code, first GitHub pull request...

This pull request incorporates the XRADIO driver from [fifteenhex/xradio](https://github.com/fifteenhex/xradio) and the Orange Pi Zero kernel [fifteenhex/linux](https://github.com/fifteenhex/linux/)

The only original work here is `drivers/net/wireless/allwinner/Kconfig` and `drivers/net/wireless/allwinner/Makefile` for the XR819 driver to compile within the kernel source. Everything else comes from the above repositories.

linux-49-xradio

The kernel has been built using the supplied configuration and tested on an Orange Pi Zero with the XR819.

The only thing I'm not sure about is where the firmware comes from. I couldn't find it in the `fifteenhex/linux` repo.

I also thought that keeping the driver name `XRADIO` was perhaps a bad idea, in case there are additional chips from Allwinner under the XRADIO name. Hence, the driver is called XR819 in the kernel configuration. The module is still called `xradio_wlan.ko` as I didn't modify the module source that extensively.

Happy to improve based on suggestions!

### CODE REVIEW

**Comment by ThomasKaiser** [comment]
@megous Firmware for this new WiFi chip was contained in [Allwinner's H2 SDK](http://filez.zoobab.com/allwinner/h2/). Files are also [here](https://github.com/igorpecovnik/lib/tree/master/bin/firmware-overlay/xr819) and should go to `/lib/firmware/xr819/`

**Comment by aik** [comment]
With the extensions enabled, it does not compile:

drivers/net/wireless/xradio/wsm_firmware.c:19:2: error: implicit declaration of function ‘xradio_pm_stay_awake’ [-Werror=implicit-function-declaration]
  xradio_pm_stay_awake(&hw_priv->pm_state, 3*HZ);
  ^
drivers/net/wireless/xradio/wsm_firmware.c:19:31: error: ‘struct xr819’ has no member named ‘pm_state’
  xradio_pm_stay_awake(&hw_priv->pm_state, 3*HZ);

**Comment by halmartin** [comment]
@aik thanks a lot for pointing this out.

Can you tell me which extensions you have enabled in the kernel config for the XR819 driver?

I only tested my branch with the options selected in the menuconfig screenshot above.

Lots of other patches in this pull from other improvements. I haven't tested the tree with all these additional patches yet since we are working on another issue with the Orange Pi Zero hanging on boot: https://github.com/igorpecovnik/lib/issues/580

**Comment by aik** [comment]
CONFIG_WLAN_VENDOR_ALLWINNER=y            
CONFIG_XR819=y                            
CONFIG_XR819_SDIO=y                       
CONFIG_XR819_NON_POWER_OF_TWO_BLOCKSIZES=y
CONFIG_XR819_USE_GPIO_IRQ=y               
CONFIG_XR819_USE_EXTENSIONS=y             

and the message is:
[    3.217833] xradio_wlan mmc1:0001:1: loading /lib/firmware/xr819/sdd_xr819.bin failed with error -2
[    3.217841] xradio_wlan mmc1:0001:1: Direct firmware load for xr819/sdd_xr819.bin failed with error -2

but the message (I think) is caused by a race - the distro is remounting the rootfs (from read-only to read-write) and I think this is why the delay helps.

**Comment by megous** [comment]
Hi, I don't have Orange Pi Zero, so I don't think it's a good idea to submit this to me. You'll need to maintain the patches yourself. I only try to support Orange Pi PC/One. And I haven't even tested Orange Pi One for a while.

**Comment by halmartin** [comment]
@mehous understood. I guess I should talk to the Armbian guys about a separate kernel repo for the Zero.

**Comment by megous** [comment]
It would be best to try for mainline inclusion, because the basics here do not require anything in my branch, aside from the thermal stuff, which seem to be subtly broken on the gpio-regulator based boards anyway.

**Comment by halmartin** [comment]
@megous I'll work on getting the xradio driver cleaned up and try for mainline.

**Pull request closed without merging**
