### PR TITLE
Trivial fixes

### PR DESCRIPTION
**Pull request by vincent-legoll**
- Typoes
- Whitespace at EOL

Signed-off-by: Vincent Legoll <vincent.legoll@gmail.com>

### CODE REVIEW

**Comment by megous** [comment]
Thank you.

**Comment by vincent-legoll** [comment]
Has this been somehow lost in latest 4.10 tree ?

**Comment by megous** [comment]
Hmm, looks like it. I've merged it on github, but did not pull it locally before force pushing the new rebased stuff to github. Thanks for noticing.

**Comment by vincent-legoll** [comment]
Hey no problem, it's not as if this is really important stuff though...

**Comment by megous** [comment]
I've added it by hand anyway. :)

**Pull request merged**
