### PR TITLE
added DTS / DTSI for NanoPi-NEO

### PR DESCRIPTION
**Pull request by erazor83**
Basically I've added the DTS changes from branch 4.6 and changed some names to fit the current naming in sun8i-h3.dtsi.

I also fixed the wrong I2C address which would stop the kernel from parsing the dtb because of naming duplicates when using the same address for different items

### CODE REVIEW

**Comment by erazor83** [comment]
Any update on this?

**Comment by megous** [comment]
Sorry, I'm just too busy.

**Comment by erazor83** [comment]
no problem, just wanted to know if there is anything wrong with the patch that prevents you from merging

**Comment by bz31** [comment]
For information, cpu-freq and thermal now work on my nanopi neo (using buildroot) after applying the uboot patch from https://github.com/igorpecovnik/lib/issues/580 and changing
regulator-enable-ramp-delay = <200>; / * 1ms * /
at
regulator-ramp-delay = <50>; / * 4ms * /

schedutil governor causes some drops when streaming hi-resolution 24bit/96kHz flac audio files. ondemand works.

**Comment by erazor83** [comment]
still on the queue... I'm currently working on the neo-air and would like to update and commit other changes.

Can you please pull this request?

**Comment by rochus-keller** [comment]
I tried the patch with Nanopi Neo. I had to add the following line to sun8i-h3-nanopi.dtsi, otherwise musb-hdrc.1.auto would not show up in /sys/class/udc/:
`&usb_otg { dr_mode = "otg"; status = "okay"; };`
I still have the problem that /sys/class/udc/musb-hdrc.1.auto/is_a_peripheral = 0 even if I connect the micro USB B to a host; is_otg = 1 though. lsusb on host hangs even if I set up a device on the Neo with configfs. To conclude: close to the goal, but still not managed to make the Neo appear as HID device to the host.

**Comment by megous** [comment]
To get USB OTG working, you may need to setup vbus and id-det too in the boards dts file. You need to check with the schematics of the board, for where these lines are connected. Also use some current branch, like 4.11.

**Comment by rochus-keller** [comment]
Ok, I will give it a try and make a fork/pull request when it works.
I should have mentioned that I was using the latest commit of your 4.11 branch from within Buildroot for my test.

**Comment by rochus-keller** [comment]
I've read on the sunxi wiki that Nanopi Neo is very similar with Orangepi One. I found the following line to be correct; the pin PG12 / Ball#D1 corresponds indeed to USB0-IDDET, as it is with the Orangepi:
`usb0_id_det-gpios = <&pio 6 12 GPIO_ACTIVE_HIGH>;`
The line `usb0_vbus-supply = <&reg_usb0_vbus>;` needs more investigations though. Before I spend much time I wondered myself if anyone has really managed to successfully run the Orangepi One in OTG peripheral mode using the 4.11 branch herein.

**Comment by megous** [comment]
I did.

**Comment by megous** [comment]
Also please, don't send pull request here. Send the patch to linux-sunxi maintainers.

http://linux-sunxi.org/Sending_patches

**Comment by rochus-keller** [comment]
Ok, thanks. Knowing that the dts of Orangepi One really work I compared more aspects of its schematics to Neo. H3 pin PL2 of Neo is not connected, so there is nothing I could reference in `usb0_vbus-supply`; the binding documentation declares it as optional, so I left it out; the kernel reports "usb_phy_generic usb_phy_generic.0.auto: usb_phy_generic.0.auto supply vcc not found, using dummy regulator" which can be ignored according to forum discussions; /sys/class/udc/musb-hdrc.1.auto is present, but is_a_peripheral is still 0; if I compile the kernel with CONFIG_USB_MUSB_GADGET=y (instead of CONFIG_USB_MUSB_DUAL_ROLE=y) and set dr_mode = "peripheral", then is_otg becomes 0, but is_a_peripheral is still 0 too; so still no solution and no patch to publish. Currently I try to find out in phy-sun4i-usb.c and sinxi.c what could be wrong. Maybe someone has a better idea.

**Pull request closed without merging**
